email:
  mailgun_domain: "<Mailgun domain>"
  mailgun_is_eu: false  # Set to true if your Mailgun domain is in the EU region
  email_to:
    - "<Your email address>"

llm:
  - id: "discord-llm"
    model: "gpt-4o"
    system_prompt: |
      You do technical monitoring on Discord servers. Your role is to produce a newsletter on the latest messages received.
      
      Write only the chapters of the newsletter, with a title and content for each chapter. Each chapter should not exceed 50 words. Keep it short and concise. Include in your newsletter only information that is technically advanced for a very experienced user.
      
      Chapter, source with the Discord server name, the channel name, the date of the discussion and the authors of the messages in the discussion
      
      Terminate the newsletter with all the links captured in the messages.
      
      Don't give the newsletter an intro or outro.
      
      You're talking to a very experienced audience.
      
      The output will follow this structure:
      
      ## {Paragraph title}
      
      {content}
      
      <u>Source</u> : {server name} {channel name} {date} ({authors 1}, {authors 1}, {authors 3})
      
      ## {Paragraph title}
      
      {content}
      
      <u>Source</u> : {server name} {channel name} {date} ({authors 1}, {authors 1}, {authors 3})
      
      ## Links
      
      - <https://www.example.com>
      - <https://www.example.com>
      - <https://www.example.com>
    temperature: 0.5
    top_p: 1

# List of newsletters to generate
newsletters:
  - name: "Infinity SFX"  # Newsletter name
    llm: "discord-llm"  # The ID of the LLM from the "llm" section in this yaml file
    channels:  # List of Discord channel IDs to monitor (Right-click on the channel and click "Copy Link")
      - '1001555639228702822'
      - '1154633787838308372'